apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: mtg-fsdatasets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: registry.sb.upf.edu/mtg/nginx:1.21.3
          name: nginx
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "300m"
          volumeMounts:
            - mountPath: /static
              name: fsdatasets-static
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx
              subPath: freesound_datasets.conf
      restartPolicy: Always
      volumes:
        - name: fsdatasets-static
          persistentVolumeClaim:
            claimName: fsdatasets-static
        - name: nginx
          configMap:
            name: nginx
      imagePullSecrets:
        - name: fsdatasets-registry