apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mtg-fsdatasets
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis