apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: fsdatasets-mtg-fsdatasets
  namespace: mtg-fsdatasets
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      number: 80
      protocol: HTTP