apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsdatasets-static
  namespace: mtg-fsdatasets
spec:
  accessModes:
    - ReadWriteMany
  nfs:
    path: /MTG/asplab-web/asplab-shared/freesound-datasets/static
    server: 10.80.110.223